### ISSUE TITLE
Get website verified by Google

### ISSUE THREAD

**Issue by seamussmith** [worcestertechnicalhighschool/ratatoskr#129]
In order to be able to authorize more than 100 users we have to get the app verified by Google. Also the warnings make our app look sus.

**Comment by seamussmith** [comment]
We technically do not have to have Google verify our app, but if we want to change the name of our app or change our logo, we have to verify it.

**Comment by djadczak956** [comment]
@seamussmith did you start this?

**Comment by djadczak956** [comment]
[https://developers.google.com/terms/api-services-user-data-policy](Here) are the requirements.

**Comment by seamussmith** [comment]
Website is currently undergoing verification. Make sure to check ratatoskrtechhigh@gmail.com frequently

**Comment by djadczak956** [comment]
Success!
