### ISSUE TITLE
Links in emails link to the heroku-app domain instead of ratatoskr.app

### ISSUE THREAD

**Issue by seamussmith** [worcestertechnicalhighschool/ratatoskr#224]
Out of boredom, I decided to check if the app worked, and I found out that the links in the emails the app sends link to ratatoskr-meeting-system.herokuapp.com instead of ratatoskr.app.

This could be caused by the Site object in the database not being set to the correct domain. This can be changed in the Django control panel in production.

Steps to replicate:
- Make a reservation
- Receive the email confirmation email
- Observe that the link in the email sent isn't the ratatoskr.app domain

**Comment by djadczak956** [comment]
I changed it, but I cannot test it right now because WPS seems to be blocking something which prevents schedules and timeslots from being created.

**Comment by seamussmith** [comment]
So I just tested it and it seems that there is another problem:

ratatoskr.app does not redirect to www.ratatoskr.app, resulting in a timing out error when trying to visit ratatoskr.app instead of www.ratatoskr.app.

**Comment by djadczak956** [comment]
I believe that was a problem that Mr. LeBoeuf was going to fix.

**Comment by seamussmith** [comment]
eventually, he did fix it

**Comment by djadczak956** [comment]
It does not seem to be fixed. The https://ratatoskr.app/ link does not redirect to the app.

**Comment by SandraWebDev** [comment]
fixed. sometimes the redirect fails here in the building. But not outside. Regardless, the links appear to be prepending www. so we should be good to go.
