### ISSUE TITLE
Make FormModels for all forms

### ISSUE THREAD

**Issue by seamussmith** [worcestertechnicalhighschool/ratatoskr#88]
Blindly grabbing data from request.POST is not really a great practice. FormModels (which can be seen in the app.forms module) allow us to validate and clean the data we want from a form without having to write all the checks.

Django allows us to display a FormModel in a view as a form, which can make prototyping easier. Django's FormModels are kind of hard to style, though so displaying forms in this fashion in the end product might not be viable.

**Comment by jeffhow** [comment]
We can extend the built in form models, but you're using Bootstrap so extending everything is a lot of extra work. This is actually where using django-bootstrap might come in handy. Checkout the documentation: https://django-bootstrap-v5.readthedocs.io/en/latest/
